### ISSUE TITLE
Understanding the inset values

### ISSUE THREAD

**Issue by AdamGerthel** [th3rdwave/react-native-safe-area-context#23]
I just installed this package in order to fix notch problems on my app. However, I immediately stumbled upon a problem: The inset values don't make sense to me. I'm getting `top: 20` on an iPhone 7, but the iPhone 7 doesn't have any notches or unsafe areas. At the same time, a Sony Xperia phone that I'm testing with, also without any notches, has `top: 0`. See below:

![Screenshot 2019-11-09 at 13 47 58](https://user-images.githubusercontent.com/1490370/68528784-92b90c80-02f7-11ea-8399-b48d2ea95aa9.png)

What are the values based upon? Is there a way for me to be able to foresee these differences so that I can work around them? I would've expected that this library provided the size of the actual unsafe areas, and not to add seemingly arbitrary additional values.

**Update**
Ok, so I'm guessing the 20 additional pixels stem from the status bar. But why is this automatically added, and how come it's only added on iOS? The status bar is hidden in my app on both Android and iOS, so I can't really just subtract those 20px in a very convenient way.. I'm doing it this way now, but feels like a hack: `paddingTop: Platform.OS === 'ios' ? insets.top - 20 : insets.top`

**Comment by janicduplessis** [comment]
@AdamGerthel What version of iOS is on the phone? We polyfill the safe area api on older iOS versions that don't support it but it might not take status bar visibility in consideration.

**Comment by AdamGerthel** [comment]
@janicduplessis The iPhone is running 13.1.2

**Comment by janicduplessis** [comment]
Ok I can repro in snack, I'll have a look. https://snack.expo.io/@janic/restless-carrot

**Comment by janicduplessis** [comment]
I think the issue is fixed now, I cannot reproduce locally, I think expo is doing a release soon I'll check to make sure this library gets updated.

**Comment by AdamGerthel** [comment]
@janicduplessis I'm not sure I follow, the issue is reproducible in your snack (using react-native-safe-area-context 0.6.0), but you're saying the issue has already been fixed? Are you saying that this is an Expo-specific issue?

**Comment by janicduplessis** [comment]
Snack uses the expo client which includes an older version of the native code (where the bug is).

I just checked and the next expo release will include version 0.6.0 which should fix your issue.

**Comment by AdamGerthel** [comment]
Oh, I see, I was a little confused since the package.json in your Snack example lists version 0.6.0. 

Anyway, I'll just wait for the next Expo release then. Thanks!

**Comment by AdamGerthel** [comment]
I've upgraded Expo and I'm using `0.6.0` but the issue persists. Your snack has the same issue still.

**Comment by janicduplessis** [comment]
@AdamGerthel Is this still an issue?

**Comment by AdamGerthel** [comment]
It's been a while since I work of those parts of the code but... seems like it, yes.

**Comment by janicduplessis** [comment]
Thanks, I just checked and I can confirm it still happens, will look at it again.

**Comment by janicduplessis** [comment]
Weird, I can still repro in snack but not locally in my example app. This is going to be hard to investigate.

**Comment by tanteemmie** [comment]
is this perhaps the same issue? #170

**Comment by devscipline** [comment]
Any update on this issue?

**Comment by Khuongnb** [comment]
Confirm issue still exist in iOS when controlling `hidden` props of StatusBar with state
