### ISSUE TITLE
CocoaPods could not find compatible versions for pod "react-native-safe-area-context"

### ISSUE THREAD

**Issue by Md-Mudassir47** [th3rdwave/react-native-safe-area-context#374]
Since this morning it started to throw this err, i'm using `"react-native": "^0.67.4",` `xcode 14.2` & `react-native-safe-area-context": "^4.3.1",` tried updating the package but again same error.. i saw that few had also raised this issue last year and setting the platform version to 11 had fixed it for them. 
```
[!] CocoaPods could not find compatible versions for pod "react-native-safe-area-context":
  In Podfile:
    react-native-safe-area-context (from `../node_modules/react-native-safe-area-context`)

Specs satisfying the `react-native-safe-area-context (from `../node_modules/react-native-safe-area-context`)` dependency were found, but they required a higher minimum deployment target.
```

`platform :ios, '12.0'` // can't set to 11 as the latest xcode expects 12 to be set as minimum.

**Comment by ersanjayparmar** [comment]
please try this

**Comment by ersanjayparmar** [comment]
please try this step:-

**Comment by ersanjayparmar** [comment]
Please try these steps:- 
1)please check versions of "react-native-safe-area-context"
     using this command 
     npm list react-native-safe-area-context 
   result   
     warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ react-native-safe-area-context@4.4.1 
  └─ react-native-safe-area-context@4.5.1
✨  Done in 0.90s.

 2 ) run this command npm dedupe 
 
 3) please recheck  versions of "react-native-safe-area-context"
 using this command 
     npm list react-native-safe-area-context 
     result
 Filtering by arguments is deprecated. Please use the pattern option instead.
└─ react-native-safe-area-context@4.4.1 

after that run command "npx react-native run-ios"
Please try these steps:- 
1)please check versions of "react-native-safe-area-context"
     using this command 
     npm list react-native-safe-area-context 
   result   
     warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ react-native-safe-area-context@4.4.1 
  └─ react-native-safe-area-context@4.5.1
✨  Done in 0.90s.

 2 ) run this command npm dedupe 
 
 3) please recheck  versions of "react-native-safe-area-context"
 using this command 
     npm list react-native-safe-area-context 
     result
 Filtering by arguments is deprecated. Please use the pattern option instead.
└─ react-native-safe-area-context@4.4.1 

after that run command "npx react-native run-ios"

**Comment by Md-Mudassir47** [comment]
@ersanjayparmar Tried the above steps but the issue still persists.

**Comment by Dat-Mobile** [comment]
Remove the ^ in version fixed for me. I'm using

`"react-native-safe-area-context": "4.3.4"`

**Comment by Md-Mudassir47** [comment]
> Remove the ^ in version fixed for me. I'm using
> 
> `"react-native-safe-area-context": "4.3.4"`

did'nt work for `v4.5.1` but worked for `v4.3.1`

**Comment by ersanjayparmar** [comment]
after Step 2 you need to install specific version of ""react-native-safe-area-context"
using npm install react-native-safe-area-context@4.4.1 its defiantly working for you

**Comment by vishpatil1999** [comment]
Update pod file update ios compatible version 
platform :ios, '13.0'

**Comment by baha-udin** [comment]
https://github.com/th3rdwave/react-native-safe-area-context/issues/374#issuecomment-1506371764

update platform :ios '11.0' to  platform :ios '13.0'

work also on me

**Comment by jmada** [comment]
> platform :ios '11.0' to platform :ios '13.0'



> [#374 (comment)](https://github.com/th3rdwave/react-native-safe-area-context/issues/374#issuecomment-1506371764)
> 
> update platform :ios '11.0' to platform :ios '13.0'
> 
> work also on me

I can confirm, changing
platform :ios '11.0' to platform :ios '13.0'
in the file ios/Podfile file
Worked like a charm!

**Comment by manojalwisnz** [comment]
update platform :ios '11.0' to platform :ios '13.0' works for me.

**Comment by owonie** [comment]
update platform :ios '11.0' to '13.0' works for me  :)

**Comment by jwasden** [comment]
Chiming in to say update platform :ios '11.0' to '13.0' works for me. I see a trend.. ;)
