### ISSUE TITLE
Extra padding with reactnavigation on android

### ISSUE THREAD

**Issue by toytonic** [th3rdwave/react-native-safe-area-context#87]
Sorry, for the short bug report as I can only describe it for now:

After upgrading from `v0.7.3` to anything above `v1.0.0` I'm seeing an extra padding in stack navigators on android. I goes away as soon as I tap into a text field.

Downgrading fixes the issue.

**Comment by janicduplessis** [comment]
Hi, I'll need a bit more info to figure this out. Also if you can provide screenshots it would help a lot.

What version of react-navigation are you using?
What is the extra padding? (top, bottom)

**Comment by toytonic** [comment]
Hi, 
the padding ist added in the top navigation/title bar of a stack navigator. Will try to make a screencast tomorrow.

I'm using:
- react-navigation v4.3.9
- react-navigation-stack  v2.5.1

Thanks for looking into it!

**Comment by NelsonPRSousa** [comment]
Today I tried to upgrade from 1.0.0 to 2.0.3 and got the same problem on Android:
![image](https://user-images.githubusercontent.com/8364345/83017112-ff3cf400-a01a-11ea-998d-19a78081706c.png)

```javascript
import * as React from 'react';
import { Text, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { createStackNavigator } from '@react-navigation/stack';

function Demo() {
    return (
        <SafeAreaView
            style={{
                flex: 1,
                justifyContent: 'space-between',
                alignItems: 'center',
            }}
        >
            <View
                style={{
                    flex: 1,
                    justifyContent: 'space-between',
                    alignItems: 'center',
                }}
            >
                <Text>This is top text.</Text>
                <Text>This is bottom text.</Text>
            </View>
        </SafeAreaView>
    );
}
const SearchStack = createStackNavigator();

const SearchStackScreen = () => (
    <SearchStack.Navigator screenOptions={{ headerShown: false }}>
        <SearchStack.Screen name="Demo" component={Demo} />
    </SearchStack.Navigator>
);
const Tab = createBottomTabNavigator();

export default function App() {
    return (
        <SafeAreaProvider>
            <NavigationContainer>
                <Tab.Navigator>
                    <Tab.Screen name="Demo" component={SearchStackScreen} />
                    {/* <Tab.Screen name="PhotoMode" component={PhotoMode} /> */}
                    {/* <Tab.Screen name="Profile" component={Profile} /> */}
                </Tab.Navigator>
            </NavigationContainer>
        </SafeAreaProvider>
    );
}
```

```json
{
    "name": "Wanderlust",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "start": "react-native start",
        "test": "jest",
        "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
    },
    "dependencies": {
        "@react-native-community/masked-view": "^0.1.10",
        "@react-navigation/bottom-tabs": "^5.5.0",
        "@react-navigation/material-top-tabs": "^5.2.8",
        "@react-navigation/native": "^5.4.3",
        "@react-navigation/stack": "^5.4.0",
        "appcenter": "3.0.2",
        "appcenter-analytics": "3.0.2",
        "appcenter-crashes": "3.0.2",
        "axios": "^0.19.2",
        "axios-mock-adapter": "^1.18.1",
        "react": "16.11.0",
        "react-native": "0.62.2",
        "react-native-gesture-handler": "^1.6.1",
        "react-native-reanimated": "^1.9.0",
        "react-native-safe-area-context": "^2.0.3",
        "react-native-screens": "^2.8.0",
        "react-native-snap-carousel": "4.0.0-beta.4",
        "react-native-tab-view": "^2.14.0",
        "react-native-vector-icons": "^6.6.0",
        "rn-placeholder": "^3.0.0",
        "styled-components": "^5.1.0"
    },
    "devDependencies": {
        "@babel/core": "^7.6.2",
        "@babel/runtime": "^7.6.2",
        "@react-native-community/eslint-config": "^1.0.0",
        "@types/jest": "^24.0.24",
        "@types/node": "^13.13.5",
        "@types/react-native": "^0.62.0",
        "@types/react-native-snap-carousel": "^3.8.1",
        "@types/react-native-vector-icons": "^6.4.5",
        "@types/react-test-renderer": "16.9.2",
        "@types/styled-components": "^5.1.0",
        "@typescript-eslint/eslint-plugin": "^2.27.0",
        "@typescript-eslint/parser": "^2.27.0",
        "babel-jest": "^24.9.0",
        "babel-plugin-module-resolver": "^4.0.0",
        "babel-plugin-styled-components": "^1.10.7",
        "eslint": "^7.0.0",
        "eslint-config-airbnb": "^18.1.0",
        "eslint-config-prettier": "^6.11.0",
        "eslint-import-resolver-babel-module": "^5.1.2",
        "eslint-plugin-import": "^2.20.2",
        "eslint-plugin-jsx-a11y": "^6.2.3",
        "eslint-plugin-prettier": "^3.1.3",
        "eslint-plugin-react": "^7.19.0",
        "husky": "^4.2.5",
        "jest": "^24.9.0",
        "metro-react-native-babel-preset": "^0.58.0",
        "prettier": "^2.0.5",
        "pretty-quick": "^2.0.1",
        "react-test-renderer": "16.11.0",
        "typescript": "^3.8.3",
        "typescript-styled-plugin": "^0.15.0"
    },
    "jest": {
        "preset": "react-native",
        "moduleFileExtensions": [
            "ts",
            "tsx",
            "js",
            "jsx",
            "json",
            "node"
        ]
    },
    "husky": {
        "hooks": {
            "pre-commit": "pretty-quick --staged && yarn run lint"
        }
    }
}
```

**Comment by janicduplessis** [comment]
I just released 3.0 which should make SafeAreaView behave like it was in 1.0. Also in you have extra insets you can always use the `edges` prop to control which edge insets are applied to.

For example to disable the top edge you can use `<SafeAreaView edges={['left', 'right', 'bottom']} />`.

**Comment by NelsonPRSousa** [comment]
> I just released 3.0 which should make SafeAreaView behave like it was in 1.0. Also if you have extra insets you can always use the `edges` prop to control which edge insets are applied to.
> 
> For example to disable the top edge you can use `<SafeAreaView edges={['left', 'right', 'bottom']} />`.
Thank you, will try it in a couple of hours and I'll let you know.

Regarding disabling the top edge, if we disable it, we lose the "SafeArea", right? We could end up with content overlapping notches?

**Comment by janicduplessis** [comment]
Yes, disabling works if you know for sure the view will never overlap a particular edge.

**Comment by NelsonPRSousa** [comment]
Tried with 3.0.1 but got this compilation error:
````
C:\src\github\private\myapp-app\node_modules\react-native-safe-area-context
\android\src\main\java\com\th3rdwave\safeareacontext\SafeAreaView.java:12: error
: cannot find symbol
import com.facebook.react.util.RNLog;
                              ^
  symbol:   class RNLog
  location: package com.facebook.react.util
C:\src\github\private\myapp-app\node_modules\react-native-safe-area-context
\android\src\main\java\com\th3rdwave\safeareacontext\SafeAreaView.java:91: error
: cannot find symbol
        RNLog.w(getReactContext(this), "SafeAreaView: Timed out waiting for layo
ut.");
        ^
  symbol:   variable RNLog
  location: class SafeAreaView
2 errors

FAILURE: Build failed with an exception.
```

Maybe there's breaking changes that I am not aware of 😅

**Comment by janicduplessis** [comment]
Oups sorry about that, fixed in 3.0.2

**Comment by NelsonPRSousa** [comment]
Tested and it is working as expected. I believe you can close this issue 👍 , what do you think @toytonic?

Awesome job, thank you @janicduplessis 🚀

**Comment by prashantchothani** [comment]
Installed the latest version and am unable to make the image come over the Status bar on left right of the notch. Can you help how to use this in the latest version ?

**Comment by toytonic** [comment]
@janicduplessis Looks good to me now. Can be closed from my point of view. Thanks a lot!

**Comment by iamvinny** [comment]
It seems like this problem is back, notice the padding below the dynamic island.

<img width="641" height="215" alt="Image" src="https://github.com/user-attachments/assets/1a8f762e-13d8-4ab5-a054-515d2946d36a" />
